export type ItemTemplate = {
	entry: number;
	patch: number;
	class: number;
	subclass: number;
	name: string;
	description: string;
	display_id: number;
	quality: number;
	flags: number;
	buy_count: number;
	buy_price: number;
	sell_price: number;
	inventory_type: number;
	allowable_class: number;
	allowable_race: number;
	item_level: number;
	required_level: number;
	required_skill: number;
	required_skill_rank: number;
	required_spell: number;
	required_honor_rank: number;
	required_city_rank: number;
	required_reputation_faction: number;
	required_reputation_rank: number;
	max_count: number;
	stackable: number;
	container_slots: number;
	stat_type1: number;
	stat_value1: number;
	stat_type2: number;
	stat_value2: number;
	stat_type3: number;
	stat_value3: number;
	stat_type4: number;
	stat_value4: number;
	stat_type5: number;
	stat_value5: number;
	stat_type6: number;
	stat_value6: number;
	stat_type7: number;
	stat_value7: number;
	stat_type8: number;
	stat_value8: number;
	stat_type9: number;
	stat_value9: number;
	stat_type10: number;
	stat_value10: number;
	delay: number;
	range_mod: number;
	ammo_type: number;
	dmg_min1: number;
	dmg_max1: number;
	dmg_type1: number;
	dmg_min2: number;
	dmg_max2: number;
	dmg_type2: number;
	dmg_min3: number;
	dmg_max3: number;
	dmg_type3: number;
	dmg_min4: number;
	dmg_max4: number;
	dmg_type4: number;
	dmg_min5: number;
	dmg_max5: number;
	dmg_type5: number;
	block: number;
	armor: number;
	holy_res: number;
	fire_res: number;
	nature_res: number;
	frost_res: number;
	shadow_res: number;
	arcane_res: number;
	spellid_1: number;
	spelltrigger_1: number;
	spellcharges_1: number;
	spellppmrate_1: number;
	spellcooldown_1: number;
	spellcategory_1: number;
	spellcategorycooldown_1: number;
	spellid_2: number;
	spelltrigger_2: number;
	spellcharges_2: number;
	spellppmrate_2: number;
	spellcooldown_2: number;
	spellcategory_2: number;
	spellcategorycooldown_2: number;
	spellid_3: number;
	spelltrigger_3: number;
	spellcharges_3: number;
	spellppmrate_3: number;
	spellcooldown_3: number;
	spellcategory_3: number;
	spellcategorycooldown_3: number;
	spellid_4: number;
	spelltrigger_4: number;
	spellcharges_4: number;
	spellppmrate_4: number;
	spellcooldown_4: number;
	spellcategory_4: number;
	spellcategorycooldown_4: number;
	spellid_5: number;
	spelltrigger_5: number;
	spellcharges_5: number;
	spellppmrate_5: number;
	spellcooldown_5: number;
	spellcategory_5: number;
	spellcategorycooldown_5: number;
	bonding: number;
	page_text: number;
	page_language: number;
	page_material: number;
	start_quest: number;
	lock_id: number;
	material: number;
	sheath: number;
	random_property: number;
	set_id: number;
	max_durability: number;
	area_bound: number;
	map_bound: number;
	duration: number;
	bag_family: number;
	disenchant_id: number;
	food_type: number;
	min_money_loot: number;
	max_money_loot: number;
	extra_flags: number;
	other_team_entry: number;
	script_name: string | null;
};

export const InitialItemTemplate = (): Omit<ItemTemplate, 'entry'> => ({
	patch: 0,
	class: 0,
	subclass: 0,
	name: '',
	description: '',
	display_id: 0,
	quality: 0,
	flags: 0,
	buy_count: 1,
	buy_price: 0,
	sell_price: 0,
	inventory_type: 0,
	allowable_class: -1,
	allowable_race: -1,
	item_level: 0,
	required_level: 0,
	required_skill: 0,
	required_skill_rank: 0,
	required_spell: 0,
	required_honor_rank: 0,
	required_city_rank: 0,
	required_reputation_faction: 0,
	required_reputation_rank: 0,
	max_count: 0,
	stackable: 1,
	container_slots: 0,
	stat_type1: 0,
	stat_value1: 0,
	stat_type2: 0,
	stat_value2: 0,
	stat_type3: 0,
	stat_value3: 0,
	stat_type4: 0,
	stat_value4: 0,
	stat_type5: 0,
	stat_value5: 0,
	stat_type6: 0,
	stat_value6: 0,
	stat_type7: 0,
	stat_value7: 0,
	stat_type8: 0,
	stat_value8: 0,
	stat_type9: 0,
	stat_value9: 0,
	stat_type10: 0,
	stat_value10: 0,
	delay: 1000,
	range_mod: 0,
	ammo_type: 0,
	dmg_min1: 0,
	dmg_max1: 0,
	dmg_type1: 0,
	dmg_min2: 0,
	dmg_max2: 0,
	dmg_type2: 0,
	dmg_min3: 0,
	dmg_max3: 0,
	dmg_type3: 0,
	dmg_min4: 0,
	dmg_max4: 0,
	dmg_type4: 0,
	dmg_min5: 0,
	dmg_max5: 0,
	dmg_type5: 0,
	block: 0,
	armor: 0,
	holy_res: 0,
	fire_res: 0,
	nature_res: 0,
	frost_res: 0,
	shadow_res: 0,
	arcane_res: 0,
	spellid_1: 0,
	spelltrigger_1: 0,
	spellcharges_1: 0,
	spellppmrate_1: 0,
	spellcooldown_1: -1,
	spellcategory_1: 0,
	spellcategorycooldown_1: -1,
	spellid_2: 0,
	spelltrigger_2: 0,
	spellcharges_2: 0,
	spellppmrate_2: 0,
	spellcooldown_2: -1,
	spellcategory_2: 0,
	spellcategorycooldown_2: -1,
	spellid_3: 0,
	spelltrigger_3: 0,
	spellcharges_3: 0,
	spellppmrate_3: 0,
	spellcooldown_3: -1,
	spellcategory_3: 0,
	spellcategorycooldown_3: -1,
	spellid_4: 0,
	spelltrigger_4: 0,
	spellcharges_4: 0,
	spellppmrate_4: 0,
	spellcooldown_4: -1,
	spellcategory_4: 0,
	spellcategorycooldown_4: -1,
	spellid_5: 0,
	spelltrigger_5: 0,
	spellcharges_5: 0,
	spellppmrate_5: 0,
	spellcooldown_5: 0,
	spellcategory_5: 0,
	spellcategorycooldown_5: 0,
	bonding: 0,
	page_text: 0,
	page_language: 0,
	page_material: 0,
	start_quest: 0,
	lock_id: 0,
	material: 0,
	sheath: 0,
	random_property: 0,
	set_id: 0,
	max_durability: 0,
	area_bound: 0,
	map_bound: 0,
	duration: 0,
	bag_family: 0,
	disenchant_id: 0,
	food_type: 0,
	min_money_loot: 0,
	max_money_loot: 0,
	extra_flags: 0,
	other_team_entry: 1,
	script_name: null,
});
