export type Conditions = {
	condition_entry: number;
	type: number;
	value1: number;
	value2: number;
	value3: number;
	value4: number;
	flags: number;
};

export type CreatureTemplate = {
	entry: number;
	patch: number;
	display_id1: number;
	display_id2: number;
	display_id3: number;
	display_id4: number;
	display_scale1: number;
	display_scale2: number;
	display_scale3: number;
	display_scale4: number;
	display_probability1: number;
	display_probability2: number;
	display_probability3: number;
	display_probability4: number;
	display_total_probability: number;
	// TODO: mount_display_id: number;
	name: string;
	subname: string | null;
	// TODO: gossip_menu_id: number;
	level_min: number;
	level_max: number;
	health_min: number;
	health_max: number;
	mana_min: number;
	mana_max: number;
	armor: number;
	faction: number;
	npc_flags: number;
	speed_walk: number;
	speed_run: number;
	detection_range: number;
	call_for_help_range: number;
	leash_range: number;
	rank: number;
	xp_multiplier: number;
	dmg_min: number;
	dmg_max: number;
	dmg_school: number;
	attack_power: number;
	dmg_multiplier: number;
	base_attack_time: number;
	ranged_attack_time: number;
	unit_class: number;
	unit_flags: number;
	dynamic_flags: number;
	beast_family: number;
	trainer_type: number;
	trainer_spell: number;
	trainer_class: number;
	trainer_race: number;
	ranged_dmg_min: number;
	ranged_dmg_max: number;
	ranged_attack_power: number;
	type: number;
	type_flags: number;
	loot_id: number;
	pickpocket_loot_id: number;
	skinning_loot_id: number;
	holy_res: number;
	fire_res: number;
	nature_res: number;
	frost_res: number;
	shadow_res: number;
	arcane_res: number;
	spell_id1: number;
	spell_id2: number;
	spell_id3: number;
	spell_id4: number;
	spell_list_id: number;
	pet_spell_list_id: number;
	auras: string | null;
	gold_min: number;
	gold_max: number;
	ai_name: string;
	movement_type: number;
	inhabit_type: number;
	civilian: number;
	racial_leader: number;
	regeneration: number;
	equipment_id: number;
	trainer_id: number;
	vendor_id: number;
	mechanic_immune_mask: number;
	school_immune_mask: number;
	flags_extra: number;
	script_name: string;
};
